import os
import json
from typing import Dict, Any, Tuple


def infer_var_meta(var_name: str) -> Dict[str, Any]:
    upper = var_name.upper()

    if "PORT" in upper:
        return {
            "type": "integer",
            "example": "3000",
            "description": "Application server port",
            "required": True,
        }

    if "URL" in upper or "URI" in upper:
        example = (
            "postgresql://user:password@localhost:5432/dbname"
            if ("DB" in upper or "DATABASE" in upper)
            else "redis://localhost:6379"
            if "REDIS" in upper
            else "https://example.com/api"
        )
        return {
            "type": "url",
            "example": example,
            "description": f"Service URL for {var_name}",
            "required": True,
        }

    if "JWT" in upper or "JWT_SECRET" in upper:
        return {
            "type": "secret",
            "example": "replace_with_32_character_minimum_random_secret_string_here",
            "description": "JWT signing secret (minimum 32 characters required by dotvet)",
            "required": True,
        }

    if any(k in upper for k in ("SECRET", "KEY", "TOKEN", "AUTH", "PASS")):
        return {
            "type": "secret",
            "example": "replace_with_cryptographically_secure_token",
            "description": f"API key or secret token for {var_name}",
            "required": True,
        }

    if (
        upper.startswith("IS_")
        or upper.startswith("HAS_")
        or upper.startswith("ENABLE_")
        or upper.startswith("DISABLE_")
        or "DEBUG" in upper
    ):
        return {
            "type": "boolean",
            "example": "false",
            "description": f"Boolean feature flag for {var_name}",
            "required": False,
        }

    return {
        "type": "string",
        "example": "value",
        "description": f"Configuration value for {var_name}",
        "required": True,
    }


def generate_env_example(var_map: Dict[str, Any]) -> str:
    lines = [
        "# .env.example",
        "# Auto-generated by dotvet (https://github.com/EthicCodes/dotvet)",
        "# Copy this file to .env and replace with your local secrets.",
        "",
    ]
    for name in sorted(var_map.keys()):
        meta = infer_var_meta(name)
        lines.append(f"# {meta['description']}")
        lines.append(f"{name}={meta['example']}")
        lines.append("")

    return "\n".join(lines)


def generate_schema(var_map: Dict[str, Any]) -> str:
    schema = {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "title": "Environment Variable Contract",
        "description": "Auto-generated by dotvet",
        "type": "object",
        "required": [],
        "properties": {},
    }

    for name in sorted(var_map.keys()):
        meta = infer_var_meta(name)
        if meta["required"]:
            schema["required"].append(name)
        is_int = meta["type"] == "integer"
        default_val: Any = meta["example"]
        if is_int:
            try:
                default_val = int(default_val)
            except (ValueError, TypeError):
                pass

        schema["properties"][name] = {
            "type": "integer" if is_int else "string",
            "description": meta["description"],
            "default": default_val,
        }
        if meta["type"] == "secret":
            schema["properties"][name]["minLength"] = 32 if "JWT" in name else 16

    return json.dumps(schema, indent=2) + "\n"


def write_generated_files(root_dir: str, var_map: Dict[str, Any]) -> Tuple[str, str]:
    example_content = generate_env_example(var_map)
    schema_content = generate_schema(var_map)

    example_path = os.path.join(root_dir, ".env.example")
    schema_path = os.path.join(root_dir, ".env.schema.json")

    with open(example_path, "w", encoding="utf-8") as f:
        f.write(example_content)
    with open(schema_path, "w", encoding="utf-8") as f:
        f.write(schema_content)

    return example_path, schema_path
