import os
from typing import Dict, Any

HOOK_SCRIPT = """#!/bin/sh
# Auto-generated by dotvet pre-commit hook
echo "🛡️ Running dotvet security gate before commit..."

if command -v dotvet >/dev/null 2>&1; then
  dotvet check --strict
  STATUS=$?
elif command -v npx >/dev/null 2>&1; then
  npx dotvet check --strict
  STATUS=$?
else
  echo "⚠️ dotvet not found in PATH, skipping pre-commit env audit."
  STATUS=0
fi

if [ $STATUS -ne 0 ]; then
  echo "❌ dotvet detected environment/secret security violations! Commit rejected."
  echo "💡 Run 'dotvet fix' or 'npx dotvet fix' to auto-repair."
  exit 1
fi
"""


def install_git_hook(root_dir: str = ".") -> Dict[str, Any]:
    git_dir = os.path.join(root_dir, ".git")
    if not os.path.exists(git_dir):
        return {"ok": False, "error": "Not a git repository (.git folder not found)."}

    hooks_dir = os.path.join(git_dir, "hooks")
    os.makedirs(hooks_dir, exist_ok=True)

    hook_file = os.path.join(hooks_dir, "pre-commit")
    with open(hook_file, "w", encoding="utf-8") as f:
        f.write(HOOK_SCRIPT)

    try:
        os.chmod(hook_file, 0o755)
    except Exception:
        pass

    return {"ok": True, "hookPath": hook_file}
