import fs from 'fs';
import path from 'path';

/**
 * Infer type and template default value from variable name.
 */
export function inferVarMeta(varName) {
  const upper = varName.toUpperCase();

  if (upper.includes('PORT')) {
    return {
      type: 'integer',
      example: '3000',
      description: 'Application server port',
      required: true
    };
  }

  if (upper.includes('URL') || upper.includes('URI')) {
    return {
      type: 'url',
      example: upper.includes('DB') || upper.includes('DATABASE')
        ? 'postgresql://user:password@localhost:5432/dbname'
        : upper.includes('REDIS')
        ? 'redis://localhost:6379'
        : 'https://example.com/api',
      description: `Service URL for ${varName}`,
      required: true
    };
  }

  if (upper.includes('JWT') || upper.includes('JWT_SECRET')) {
    return {
      type: 'secret',
      example: 'replace_with_32_character_minimum_random_secret_string_here',
      description: 'JWT signing secret (minimum 32 characters required by dotvet)',
      required: true
    };
  }

  if (
    upper.includes('SECRET') ||
    upper.includes('KEY') ||
    upper.includes('TOKEN') ||
    upper.includes('AUTH') ||
    upper.includes('PASS')
  ) {
    return {
      type: 'secret',
      example: 'replace_with_cryptographically_secure_token',
      description: `API key or secret token for ${varName}`,
      required: true
    };
  }

  if (
    upper.startsWith('IS_') ||
    upper.startsWith('HAS_') ||
    upper.startsWith('ENABLE_') ||
    upper.startsWith('DISABLE_') ||
    upper.includes('DEBUG')
  ) {
    return {
      type: 'boolean',
      example: 'false',
      description: `Boolean feature flag for ${varName}`,
      required: false
    };
  }

  return {
    type: 'string',
    example: 'value',
    description: `Configuration value for ${varName}`,
    required: true
  };
}

/**
 * Generate .env.example content.
 */
export function generateEnvExample(varMap) {
  const lines = [
    '# .env.example',
    '# Auto-generated by dotvet (https://github.com/EthicCodeTech/dotvet)',
    '# Copy this file to .env and replace with your local secrets.',
    ''
  ];

  const sortedVars = Array.from(varMap.keys()).sort();
  for (const name of sortedVars) {
    const meta = inferVarMeta(name);
    lines.push(`# ${meta.description}`);
    lines.push(`${name}=${meta.example}`);
    lines.push('');
  }

  return lines.join('\n');
}

/**
 * Generate .env.schema.json content.
 */
export function generateSchema(varMap) {
  const schema = {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    title: 'Environment Variable Contract',
    description: 'Auto-generated by dotvet',
    type: 'object',
    required: [],
    properties: {}
  };

  const sortedVars = Array.from(varMap.keys()).sort();
  for (const name of sortedVars) {
    const meta = inferVarMeta(name);
    if (meta.required) {
      schema.required.push(name);
    }
    const isInteger = meta.type === 'integer';
    let defaultValue = meta.example;
    if (isInteger) {
      const parsed = parseInt(defaultValue, 10);
      if (!isNaN(parsed)) {
        defaultValue = parsed;
      }
    }

    schema.properties[name] = {
      type: isInteger ? 'integer' : 'string',
      description: meta.description,
      default: defaultValue
    };
    if (meta.type === 'secret') {
      schema.properties[name].minLength = name.includes('JWT') ? 32 : 16;
    }
  }

  return JSON.stringify(schema, null, 2) + '\n';
}

/**
 * Write generated schema and example files to disk.
 */
export function writeGeneratedFiles(rootDir, varMap) {
  const exampleContent = generateEnvExample(varMap);
  const schemaContent = generateSchema(varMap);

  const examplePath = path.join(rootDir, '.env.example');
  const schemaPath = path.join(rootDir, '.env.schema.json');

  fs.writeFileSync(examplePath, exampleContent, 'utf8');
  fs.writeFileSync(schemaPath, schemaContent, 'utf8');

  return { examplePath, schemaPath };
}
