import fs from 'fs';
import path from 'path';

export function installGitHook(rootDir = process.cwd()) {
  const gitDir = path.join(rootDir, '.git');
  if (!fs.existsSync(gitDir)) {
    return { ok: false, error: 'Not a git repository (.git folder not found).' };
  }

  const hooksDir = path.join(gitDir, 'hooks');
  if (!fs.existsSync(hooksDir)) {
    fs.mkdirSync(hooksDir, { recursive: true });
  }

  const preCommitFile = path.join(hooksDir, 'pre-commit');
  const preCommitScript = `#!/bin/sh
# Auto-generated by dotvet pre-commit hook
echo "🛡️ Running dotvet security gate before commit..."

if command -v npx >/dev/null 2>&1; then
  npx dotvet check --strict
  STATUS=$?
elif command -v dotvet >/dev/null 2>&1; then
  dotvet check --strict
  STATUS=$?
else
  echo "⚠️ dotvet not found in PATH, skipping pre-commit env audit."
  STATUS=0
fi

if [ $STATUS -ne 0 ]; then
  echo "❌ dotvet detected environment/secret security violations! Commit rejected."
  echo "💡 Run 'npx dotvet fix' or 'dotvet fix' to auto-repair."
  exit 1
fi
`;

  const prePushFile = path.join(hooksDir, 'pre-push');
  const prePushScript = `#!/bin/sh
# Auto-generated by dotvet pre-push hook
echo "🛡️ Running dotvet pre-push firewall check..."

if command -v npx >/dev/null 2>&1; then
  npx dotvet check --strict
  STATUS=$?
elif command -v dotvet >/dev/null 2>&1; then
  dotvet check --strict
  STATUS=$?
else
  echo "⚠️ dotvet not found in PATH, skipping pre-push env audit."
  STATUS=0
fi

if [ $STATUS -ne 0 ]; then
  echo "❌ dotvet blocked git push! Insecure environment configurations or historical leaks detected."
  echo "💡 Run 'npx dotvet check' to inspect issues."
  exit 1
fi
`;

  fs.writeFileSync(preCommitFile, preCommitScript, { mode: 0o755 });
  fs.writeFileSync(prePushFile, prePushScript, { mode: 0o755 });

  return { ok: true, preCommitPath: preCommitFile, prePushPath: prePushFile, hookPath: preCommitFile };
}

